### ISSUE TITLE
책의 목차와 본 리파지토리에 올라 있는 챕터들 매치가 안 됨

### ISSUE THREAD

**Issue by eulercat** [wikibook/algorithm-math#1]
도대체 어떤 책의 소스를 올려 두신 건가요?

**Comment by eulercat** [comment]
한글 책은 전체가 5 chapter 인데, 본 소스 구성은 10 chapter 로 되어 있습니다.

**Comment by wikibook** [comment]
@eulercat 님, 안녕하세요.
위키북스 담당자입니다.

문의주신 내용을 확인해 봤는데, 실수로 다른 책의 예제 코드가 업로드되어 있었습니다.

불편을 드려 죄송하고요, 현재 해당 도서의 올바른 예제 코드로 업데이트했습니다.
그럼 확인 부탁드립니다..!

고맙습니다.

**Comment by eulercat** [comment]
빠른 처리 감사합니다. 👍
